#!/bin/bash -x
# Repack tarball because of data files with unknown license

set -e

# Remark: A new uscan that enables easier handling of removing files can be
#         obtained via
#   git clone git://tille@git.debian.org/git/users/tille/devscripts.git
#         and then copy scripts/uscan.pl as uscan at the beginning of your PATH
if uscan --help | grep -q -- --repack-compression ; then
    echo "Use new enhanced uscan"
    uscan --verbose --force-download
    exit
fi

# Falling back to manually removing files

PACKAGE=`dpkg-parsechangelog | sed -n 's/^Source: //p'`
VERSION=`dpkg-parsechangelog | sed -ne 's/^Version: \(.*\)-.*/\1/p' | sed -e 's/\+.*//'`

uscan --verbose --force-download --no-symlink

# Remove files with unclear rights
#
#  gdal/data/cubewerx_extra.wkt
#   Derived from definitions distributed by Cubewerx.
#   See http://trac.osgeo.org/gdal/ticket/2165
# 
#  gdal/data/ecw_cs.dat
#   Derived via much processing from ERMapper GDT definitions.
#   See http://trac.osgeo.org/gdal/ticket/2162
#
#  gdal/data/esri_extra.wkt
#   Derived with some processing from projections definitions in ArcGIS.
#   See http://trac.osgeo.org/gdal/ticket/2163

gunzip -c ../${PACKAGE}-${VERSION}.tar.gz | tar --delete --wildcards -vf - ${PACKAGE}-${VERSION}/data/{cubewerx_extra,ecw_cs,esri_extra}.wkt | GZIP="--best --no-name" gzip -c > ../${PACKAGE}_${VERSION}+dfsg.orig.tar.gz

